CREATE DATABASE Autoservice;
USE Autoservice;

CREATE TABLE Users(
	id INT IDENTITY(1,1) PRIMARY KEY,
	Nickname VARCHAR(25) NOT NULL,
	Pass VARCHAR(25) NOT NULL,
	User_type BIT NOT NULL,
);

CREATE TABLE CarStatus(
	id INT IDENTITY(1,1) PRIMARY KEY,
	Condition VARCHAR(50) NOT NULL,
);

CREATE TABLE Car(
	id INT IDENTITY(1,1) PRIMARY KEY,
	IsCargo BIT NOT NULL,
	Model VARCHAR(50) NOT NULL,
	CarType VARCHAR(50) NOT NULL,
	Manufacturer VARCHAR(25) NOT NULL,
	CarAssembly VARCHAR(50) NOT NULL,
	CarNumber VARCHAR(10),
	StatusId INT,
	FOREIGN KEY (StatusId) REFERENCES CarStatus (id) ON DELETE CASCADE,
);

CREATE TABLE Accounting(
	id INT IDENTITY(1, 1) PRIMARY KEY,
	CarId INT NOT NULL,
	Mileage INT,
	Comissioning INT,
	Decomissioning INT,
	EngineStatus VARCHAR(100) NOT NULL,
	ChassisStatus VARCHAR(100) NOT NULL,
	CarcassStatus VARCHAR(100) NOT NULL,
	FOREIGN KEY (CarId) REFERENCES Car (id) ON DELETE CASCADE,
);

CREATE TABLE ServiceType(
	id INT IDENTITY(1,1) PRIMARY KEY,
	TypeService VARCHAR(50) NOT NULL,
	TimePeriod VARCHAR(50) NOT NULL,
);

CREATE TABLE IntermediateTotals(
	id INT IDENTITY(1,1) PRIMARY KEY,
	CarId INT NOT NULL,
	ServiceTypeId INT NOT NULL,
	DateOfSerivce VARCHAR(50) NOT NULL,
	FOREIGN KEY (CarId) REFERENCES Car (id) ON DELETE CASCADE,
	FOREIGN KEY (ServiceTypeId) REFERENCES ServiceType (id) ON DELETE CASCADE,
);